name=finsight-raw-hdfs-sink
connector.class=io.confluent.connect.hdfs3.Hdfs3SinkConnector
tasks.max=1
topics=txn-raw

hdfs.url=hdfs://localhost:9000
topics.dir=/finsight/raw
logs.dir=/finsight/kafka-connect-logs

format.class=io.confluent.connect.hdfs3.parquet.ParquetFormat
partitioner.class=io.confluent.connect.storage.partitioner.FieldPartitioner
partition.field.name=step

flush.size=1000
rotate.interval.ms=60000

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=true

confluent.topic.bootstrap.servers=localhost:9092
confluent.topic.replication.factor=1
